// Token Whitelist
// Curated list of tokens to display in the Dream Team game
// Organized by category for easy maintenance

/**
 * Whitelist of allowed token symbols
 * These are the only tokens that will be displayed in the game
 */
export const ALLOWED_TOKENS = [
    // Major Cryptocurrencies
    'BTC', 'ETH', 'XRP', 'BNB', 'SOL', 'TRX', 'DOGE', 'ADA', 'BCH', 'LINK',
    'HYPE', 'XLM', 'XMR', 'LTC', 'SUI', 'AVAX', 'HBAR', 'ZEC', 'SHIB', 'CRO',
    'TON', 'MNT', 'UNI', 'DOT', 'AAVE', 'TAO', 'BGB', 'CC', 'NEAR',
    'ASTER', 'ETC', 'ENA', 'ICP', 'PEPE', 'PUMP', 'KAS', 'WLD', 'QNT', 'POL',
    'APT', 'ALGO', 'TRUMP', 'ARB', 'VET', 'FIL', 'ATOM',

    // DeFi & Layer 2
    'RENDER', 'SEI', 'CAKE', 'BONK', 'IP', 'JUP', 'MORPHO', 'PENGU', 'AERO',
    'MYX', 'DASH', 'OP', 'VIRTUAL', 'INJ', 'STX', 'STRK', 'XTZ', 'TIA', 'GRT',
    'ETHFI', 'FLOKI', '2Z', 'ENS', 'IOTA', 'PENDLE', 'PYTH', 'BAT', 'LUNC',
    'MERL', 'FARTCOIN', 'WIF', 'SAND', 'HNT', 'S', 'FLOW', 'JASMY', 'XPL',
    'GALA', 'THETA', 'GNO', 'CHZ', 'SYRUP', 'COMP', 'RAY', 'BORG', 'MON',
    'MANA', 'NEO', 'ZK', 'ZRO', 'ZBCN', 'PIPPIN', 'AR', '1INCH', 'CHEEMS',

    // Infrastructure & Gaming
    'EIGEN', 'WAL', 'IMX', 'RUNE', 'EGLD', 'ZORA', 'KMNO', 'WEMIX', 'W',
    'JTO', 'AXS', 'DYDX', 'SNX', 'SFP', 'MET', 'KAITO', 'QTUM', 'GRASS',
    'KSM', 'AIOZ', 'LINEA', 'RON', 'CORE', 'MOVE', 'AXL', 'AKT', 'KAVA',
    'BABYDOGE', 'MINA', 'BERA', 'DGB', 'EOS', 'H'
];

/**
 * Map of token symbols to their CoinGecko IDs
 * This helps with fetching the correct token data
 */
export const TOKEN_ID_MAP = {
    'BTC': 'bitcoin',
    'ETH': 'ethereum',
    'XRP': 'ripple',
    'BNB': 'binancecoin',
    'SOL': 'solana',
    'TRX': 'tron',
    'DOGE': 'dogecoin',
    'ADA': 'cardano',
    'BCH': 'bitcoin-cash',
    'LINK': 'chainlink',
    'HYPE': 'hyperliquid',
    'XLM': 'stellar',
    'XMR': 'monero',
    'LTC': 'litecoin',
    'SUI': 'sui',
    'AVAX': 'avalanche-2',
    'HBAR': 'hedera-hashgraph',
    'ZEC': 'zcash',
    'SHIB': 'shiba-inu',
    'CRO': 'crypto-com-chain',
    'TON': 'the-open-network',
    'MNT': 'mantle',
    'UNI': 'uniswap',
    'DOT': 'polkadot',
    'AAVE': 'aave',
    'TAO': 'bittensor',
    'BGB': 'bitget-token',
    'CC': 'canton-network',
    'NEAR': 'near',
    'ASTER': 'aster',
    'ETC': 'ethereum-classic',
    'ENA': 'ethena',
    'ICP': 'internet-computer',
    'PEPE': 'pepe',
    'PUMP': 'pump-fun',
    'KAS': 'kaspa',
    'WLD': 'worldcoin-wld',
    'QNT': 'quant-network',
    'POL': 'matic-network',
    'APT': 'aptos',
    'ALGO': 'algorand',
    'TRUMP': 'official-trump',
    'ARB': 'arbitrum',
    'VET': 'vechain',
    'FIL': 'filecoin',
    'ATOM': 'cosmos',
    'RENDER': 'render-token',
    'SEI': 'sei-network',
    'CAKE': 'pancakeswap-token',
    'BONK': 'bonk',
    'IP': 'story-protocol',
    'JUP': 'jupiter-exchange-solana',
    'MORPHO': 'morpho',
    'PENGU': 'pudgy-penguins',
    'AERO': 'aerodrome-finance',
    'MYX': 'myx-finance',
    'DASH': 'dash',
    'OP': 'optimism',
    'VIRTUAL': 'virtuals-protocol',
    'INJ': 'injective-protocol',
    'STX': 'blockstack',
    'STRK': 'starknet',
    'XTZ': 'tezos',
    'TIA': 'celestia',
    'GRT': 'the-graph',
    'ETHFI': 'ether-fi',
    'FLOKI': 'floki',
    '2Z': 'doublezero',
    'ENS': 'ethereum-name-service',
    'IOTA': 'iota',
    'PENDLE': 'pendle',
    'PYTH': 'pyth-network',
    'BAT': 'basic-attention-token',
    'LUNC': 'terra-luna',
    'MERL': 'merlin-chain',
    'FARTCOIN': 'fartcoin',
    'WIF': 'dogwifcoin',
    'SAND': 'the-sandbox',
    'HNT': 'helium',
    'S': 'sonic-2',
    'FLOW': 'flow',
    'JASMY': 'jasmycoin',
    'XPL': 'plasma-finance',
    'GALA': 'gala',
    'THETA': 'theta-token',
    'GNO': 'gnosis',
    'CHZ': 'chiliz',
    'SYRUP': 'maple',
    'COMP': 'compound-governance-token',
    'RAY': 'raydium',
    'BORG': 'swissborg',
    'MON': 'monad',
    'MANA': 'decentraland',
    'NEO': 'neo',
    'ZK': 'zksync',
    'ZRO': 'layerzero',
    'ZBCN': 'zebec-protocol',
    'PIPPIN': 'pippin',
    'AR': 'arweave',
    '1INCH': '1inch',
    'CHEEMS': 'cheems',
    'EIGEN': 'eigenlayer',
    'WAL': 'walrus',
    'IMX': 'immutable-x',
    'RUNE': 'thorchain',
    'EGLD': 'elrond-erd-2',
    'ZORA': 'zora',
    'KMNO': 'kamino',
    'WEMIX': 'wemix-token',
    'W': 'wormhole',
    'JTO': 'jito-governance-token',
    'AXS': 'axie-infinity',
    'DYDX': 'dydx-chain',
    'SNX': 'havven',
    'SFP': 'safepal',
    'MET': 'metronome',
    'KAITO': 'kaito',
    'QTUM': 'qtum',
    'GRASS': 'grass',
    'KSM': 'kusama',
    'AIOZ': 'aioz-network',
    'LINEA': 'linea',
    'RON': 'ronin',
    'CORE': 'coredaoorg',
    'MOVE': 'movement',
    'AXL': 'axelar',
    'AKT': 'akash-network',
    'KAVA': 'kava',
    'BABYDOGE': 'baby-doge-coin',
    'MINA': 'mina-protocol',
    'BERA': 'berachain-bera',
    'DGB': 'digibyte',
    'EOS': 'eos',
    'H': 'humanity-protocol'
};
